{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "               django.core.exceptions.FieldError: Cannot resolve keyword 'name_id' into field. Choices are: company, company_id, created_at, created_by, created_by_id, id, isActive, projectusers, role, role_id, updated_at, updated_by, updated_by_id, user, user_id\n", "test_name": "test_login_with_valid_data", "rerun": "0"}}, "suite_name": "usermanagement/Test_usermanagement/test_views.py"}}}, "date": "August 23, 2021", "start_time": 1629695776.6992228, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}