{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 8}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_users", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_random_user", "rerun": "0"}, "2": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py, line 54\n      @pytest.mark.parametrize(\"email,status,user_verified\",[\n      (\"testuser1@kpmg.com\",False,True),(\"testuser2@kpmg.com\",False,True),(\"testuser3@kpmg.com\",False,True),\n      (\"testuser4@kpmg.com\",True,False),(\"testuser5@kpmg.com\",True,False),(\"testuser6@kpmg.com\",True,False),\n      (\"testuser7@kpmg.com\",False,False),(\"testuser8@kpmg.com\",False,False)\n          ])\n      def test_user_status(self,email,status,user_verified,test_random_user):\nE       fixture 'test_random_user' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_company, setup_random_user, setup_roles, setup_superusers, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py:54\n", "test_name": "test_user_status[testuser1@kpmg.com-False-True]", "rerun": "0"}, "3": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py, line 54\n      @pytest.mark.parametrize(\"email,status,user_verified\",[\n      (\"testuser1@kpmg.com\",False,True),(\"testuser2@kpmg.com\",False,True),(\"testuser3@kpmg.com\",False,True),\n      (\"testuser4@kpmg.com\",True,False),(\"testuser5@kpmg.com\",True,False),(\"testuser6@kpmg.com\",True,False),\n      (\"testuser7@kpmg.com\",False,False),(\"testuser8@kpmg.com\",False,False)\n          ])\n      def test_user_status(self,email,status,user_verified,test_random_user):\nE       fixture 'test_random_user' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_company, setup_random_user, setup_roles, setup_superusers, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py:54\n", "test_name": "test_user_status[testuser2@kpmg.com-False-True]", "rerun": "0"}, "4": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py, line 54\n      @pytest.mark.parametrize(\"email,status,user_verified\",[\n      (\"testuser1@kpmg.com\",False,True),(\"testuser2@kpmg.com\",False,True),(\"testuser3@kpmg.com\",False,True),\n      (\"testuser4@kpmg.com\",True,False),(\"testuser5@kpmg.com\",True,False),(\"testuser6@kpmg.com\",True,False),\n      (\"testuser7@kpmg.com\",False,False),(\"testuser8@kpmg.com\",False,False)\n          ])\n      def test_user_status(self,email,status,user_verified,test_random_user):\nE       fixture 'test_random_user' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_company, setup_random_user, setup_roles, setup_superusers, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py:54\n", "test_name": "test_user_status[testuser3@kpmg.com-False-True]", "rerun": "0"}, "5": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py, line 54\n      @pytest.mark.parametrize(\"email,status,user_verified\",[\n      (\"testuser1@kpmg.com\",False,True),(\"testuser2@kpmg.com\",False,True),(\"testuser3@kpmg.com\",False,True),\n      (\"testuser4@kpmg.com\",True,False),(\"testuser5@kpmg.com\",True,False),(\"testuser6@kpmg.com\",True,False),\n      (\"testuser7@kpmg.com\",False,False),(\"testuser8@kpmg.com\",False,False)\n          ])\n      def test_user_status(self,email,status,user_verified,test_random_user):\nE       fixture 'test_random_user' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_company, setup_random_user, setup_roles, setup_superusers, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py:54\n", "test_name": "test_user_status[testuser4@kpmg.com-True-False]", "rerun": "0"}, "6": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py, line 54\n      @pytest.mark.parametrize(\"email,status,user_verified\",[\n      (\"testuser1@kpmg.com\",False,True),(\"testuser2@kpmg.com\",False,True),(\"testuser3@kpmg.com\",False,True),\n      (\"testuser4@kpmg.com\",True,False),(\"testuser5@kpmg.com\",True,False),(\"testuser6@kpmg.com\",True,False),\n      (\"testuser7@kpmg.com\",False,False),(\"testuser8@kpmg.com\",False,False)\n          ])\n      def test_user_status(self,email,status,user_verified,test_random_user):\nE       fixture 'test_random_user' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_company, setup_random_user, setup_roles, setup_superusers, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py:54\n", "test_name": "test_user_status[testuser5@kpmg.com-True-False]", "rerun": "0"}, "7": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py, line 54\n      @pytest.mark.parametrize(\"email,status,user_verified\",[\n      (\"testuser1@kpmg.com\",False,True),(\"testuser2@kpmg.com\",False,True),(\"testuser3@kpmg.com\",False,True),\n      (\"testuser4@kpmg.com\",True,False),(\"testuser5@kpmg.com\",True,False),(\"testuser6@kpmg.com\",True,False),\n      (\"testuser7@kpmg.com\",False,False),(\"testuser8@kpmg.com\",False,False)\n          ])\n      def test_user_status(self,email,status,user_verified,test_random_user):\nE       fixture 'test_random_user' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_company, setup_random_user, setup_roles, setup_superusers, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py:54\n", "test_name": "test_user_status[testuser6@kpmg.com-True-False]", "rerun": "0"}, "8": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py, line 54\n      @pytest.mark.parametrize(\"email,status,user_verified\",[\n      (\"testuser1@kpmg.com\",False,True),(\"testuser2@kpmg.com\",False,True),(\"testuser3@kpmg.com\",False,True),\n      (\"testuser4@kpmg.com\",True,False),(\"testuser5@kpmg.com\",True,False),(\"testuser6@kpmg.com\",True,False),\n      (\"testuser7@kpmg.com\",False,False),(\"testuser8@kpmg.com\",False,False)\n          ])\n      def test_user_status(self,email,status,user_verified,test_random_user):\nE       fixture 'test_random_user' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_company, setup_random_user, setup_roles, setup_superusers, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py:54\n", "test_name": "test_user_status[testuser7@kpmg.com-False-False]", "rerun": "0"}, "9": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py, line 54\n      @pytest.mark.parametrize(\"email,status,user_verified\",[\n      (\"testuser1@kpmg.com\",False,True),(\"testuser2@kpmg.com\",False,True),(\"testuser3@kpmg.com\",False,True),\n      (\"testuser4@kpmg.com\",True,False),(\"testuser5@kpmg.com\",True,False),(\"testuser6@kpmg.com\",True,False),\n      (\"testuser7@kpmg.com\",False,False),(\"testuser8@kpmg.com\",False,False)\n          ])\n      def test_user_status(self,email,status,user_verified,test_random_user):\nE       fixture 'test_random_user' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_company, setup_random_user, setup_roles, setup_superusers, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_models.py:54\n", "test_name": "test_user_status[testuser8@kpmg.com-False-False]", "rerun": "0"}}, "suite_name": "usermanagement/Test_usermanagement/test_models.py"}}}, "date": "August 17, 2021", "start_time": 1629207250.4642508, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "2", "fail": "0", "skip": "0", "error": "8", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "10"}