{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 1}, "tests": {"0": {"status": "ERROR", "message": "setup_saved_user = [{'active': True, 'email': 'testuser1@kpmg.com', 'first_name': 'test', 'hashkey': '79c155ec-c', ...}, {'active': True,...88-c', ...}, {'active': False, 'email': 'testuser6@kpmg.com', 'first_name': 'test', 'hashkey': 'babbbafd-3', ...}, ...]\nsetup_random_user = [{'active': True, 'email': 'testuser1@kpmg.com', 'first_name': 'test', 'hashkey': 'b2a38b08-9', ...}, {'active': True,...8d-8', ...}, {'active': False, 'email': 'testuser6@kpmg.com', 'first_name': 'test', 'hashkey': '0ca168af-0', ...}, ...]\n\n    @pytest.fixture\n    def setup_temporary_urls(setup_saved_user,setup_random_user):\n    \tusers=setup_random_user\n    \n    \tfor x in range(1,len(users)+1):\n>   \t\tgetUser=Users.objects.get(email__iexact=users[x][\"email\"])\nE     IndexError: list index out of range\n\n..\\..\\conftest.py:202: IndexError\n", "test_name": "test_temporary_url", "rerun": "0"}}, "suite_name": "usermanagement/Test_usermanagement/test_models.py"}}}, "date": "August 18, 2021", "start_time": 1629271806.2389238, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}