{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 8}, "tests": {"0": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py, line 96\n  \t@pytest.mark.parametrize(\"email,password\",[\n  \t\t(\"testuser1@kpmg.com\",\"Password@123\"),(\"testuser2@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser3@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser4@kpmg.com\",\"Password@123\"),(\"testuser5@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser6@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser7@kpmg.com\",\"Password@123\"),(\"testuser8@kpmg.com\",\"Password@123\")\n  \t\t])\n  \tdef test_login_with_invalid_attempt_reset(self,client,\nE       fixture 'setup_multiple_invalid_reset' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_activitylogs, setup_company, setup_multiple_invalid, setup_random_user, setup_register_access, setup_register_worker, setup_roles, setup_saved_user, setup_superusers, setup_temporary_urls, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py:96\n", "test_name": "test_login_with_invalid_attempt_reset[testuser1@kpmg.com-Password@123]", "rerun": "0"}, "1": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py, line 96\n  \t@pytest.mark.parametrize(\"email,password\",[\n  \t\t(\"testuser1@kpmg.com\",\"Password@123\"),(\"testuser2@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser3@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser4@kpmg.com\",\"Password@123\"),(\"testuser5@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser6@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser7@kpmg.com\",\"Password@123\"),(\"testuser8@kpmg.com\",\"Password@123\")\n  \t\t])\n  \tdef test_login_with_invalid_attempt_reset(self,client,\nE       fixture 'setup_multiple_invalid_reset' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_activitylogs, setup_company, setup_multiple_invalid, setup_random_user, setup_register_access, setup_register_worker, setup_roles, setup_saved_user, setup_superusers, setup_temporary_urls, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py:96\n", "test_name": "test_login_with_invalid_attempt_reset[testuser2@kpmg.com-Password@123]", "rerun": "0"}, "2": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py, line 96\n  \t@pytest.mark.parametrize(\"email,password\",[\n  \t\t(\"testuser1@kpmg.com\",\"Password@123\"),(\"testuser2@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser3@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser4@kpmg.com\",\"Password@123\"),(\"testuser5@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser6@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser7@kpmg.com\",\"Password@123\"),(\"testuser8@kpmg.com\",\"Password@123\")\n  \t\t])\n  \tdef test_login_with_invalid_attempt_reset(self,client,\nE       fixture 'setup_multiple_invalid_reset' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_activitylogs, setup_company, setup_multiple_invalid, setup_random_user, setup_register_access, setup_register_worker, setup_roles, setup_saved_user, setup_superusers, setup_temporary_urls, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py:96\n", "test_name": "test_login_with_invalid_attempt_reset[testuser3@kpmg.com-Password@123]", "rerun": "0"}, "3": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py, line 96\n  \t@pytest.mark.parametrize(\"email,password\",[\n  \t\t(\"testuser1@kpmg.com\",\"Password@123\"),(\"testuser2@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser3@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser4@kpmg.com\",\"Password@123\"),(\"testuser5@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser6@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser7@kpmg.com\",\"Password@123\"),(\"testuser8@kpmg.com\",\"Password@123\")\n  \t\t])\n  \tdef test_login_with_invalid_attempt_reset(self,client,\nE       fixture 'setup_multiple_invalid_reset' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_activitylogs, setup_company, setup_multiple_invalid, setup_random_user, setup_register_access, setup_register_worker, setup_roles, setup_saved_user, setup_superusers, setup_temporary_urls, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py:96\n", "test_name": "test_login_with_invalid_attempt_reset[testuser4@kpmg.com-Password@123]", "rerun": "0"}, "4": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py, line 96\n  \t@pytest.mark.parametrize(\"email,password\",[\n  \t\t(\"testuser1@kpmg.com\",\"Password@123\"),(\"testuser2@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser3@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser4@kpmg.com\",\"Password@123\"),(\"testuser5@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser6@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser7@kpmg.com\",\"Password@123\"),(\"testuser8@kpmg.com\",\"Password@123\")\n  \t\t])\n  \tdef test_login_with_invalid_attempt_reset(self,client,\nE       fixture 'setup_multiple_invalid_reset' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_activitylogs, setup_company, setup_multiple_invalid, setup_random_user, setup_register_access, setup_register_worker, setup_roles, setup_saved_user, setup_superusers, setup_temporary_urls, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py:96\n", "test_name": "test_login_with_invalid_attempt_reset[testuser5@kpmg.com-Password@123]", "rerun": "0"}, "5": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py, line 96\n  \t@pytest.mark.parametrize(\"email,password\",[\n  \t\t(\"testuser1@kpmg.com\",\"Password@123\"),(\"testuser2@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser3@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser4@kpmg.com\",\"Password@123\"),(\"testuser5@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser6@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser7@kpmg.com\",\"Password@123\"),(\"testuser8@kpmg.com\",\"Password@123\")\n  \t\t])\n  \tdef test_login_with_invalid_attempt_reset(self,client,\nE       fixture 'setup_multiple_invalid_reset' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_activitylogs, setup_company, setup_multiple_invalid, setup_random_user, setup_register_access, setup_register_worker, setup_roles, setup_saved_user, setup_superusers, setup_temporary_urls, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py:96\n", "test_name": "test_login_with_invalid_attempt_reset[testuser6@kpmg.com-Password@123]", "rerun": "0"}, "6": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py, line 96\n  \t@pytest.mark.parametrize(\"email,password\",[\n  \t\t(\"testuser1@kpmg.com\",\"Password@123\"),(\"testuser2@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser3@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser4@kpmg.com\",\"Password@123\"),(\"testuser5@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser6@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser7@kpmg.com\",\"Password@123\"),(\"testuser8@kpmg.com\",\"Password@123\")\n  \t\t])\n  \tdef test_login_with_invalid_attempt_reset(self,client,\nE       fixture 'setup_multiple_invalid_reset' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_activitylogs, setup_company, setup_multiple_invalid, setup_random_user, setup_register_access, setup_register_worker, setup_roles, setup_saved_user, setup_superusers, setup_temporary_urls, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py:96\n", "test_name": "test_login_with_invalid_attempt_reset[testuser7@kpmg.com-Password@123]", "rerun": "0"}, "7": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py, line 96\n  \t@pytest.mark.parametrize(\"email,password\",[\n  \t\t(\"testuser1@kpmg.com\",\"Password@123\"),(\"testuser2@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser3@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser4@kpmg.com\",\"Password@123\"),(\"testuser5@kpmg.com\",\"Password@123\")\n  \t\t,(\"testuser6@kpmg.com\",\"Password@123\"),\n  \t\t(\"testuser7@kpmg.com\",\"Password@123\"),(\"testuser8@kpmg.com\",\"Password@123\")\n  \t\t])\n  \tdef test_login_with_invalid_attempt_reset(self,client,\nE       fixture 'setup_multiple_invalid_reset' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_activitylogs, setup_company, setup_multiple_invalid, setup_random_user, setup_register_access, setup_register_worker, setup_roles, setup_saved_user, setup_superusers, setup_temporary_urls, setup_user, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py:96\n", "test_name": "test_login_with_invalid_attempt_reset[testuser8@kpmg.com-Password@123]", "rerun": "0"}}, "suite_name": "usermanagement/Test_usermanagement/test_views.py"}}}, "date": "August 18, 2021", "start_time": 1629292999.6981246, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "8", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "8"}