{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 2}, "tests": {"0": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py, line 524\n  \t@pytest.mark.parametrize(\"email,password,new_pass\",[\n  \t\t(\"testuser1@momenttext.com\",\"Password@123\",\"newPassword@1234\")\n  \t\t# ,(\"testuser2@momenttext.com\",\"Password@123\",\"newPassword@1234\")\n  \t\t# ,(\"testuser3@momenttext.com\",\"Password@123\",\"newPassword@1234\")\n  \t\t# ,(\"testuser4@momenttext.com\",\"Password@123\",\"newPassword@1234\")\n  \t\t# ,(\"testuser5@momenttext.com\",\"Password@123\",\"newPassword@1234\")\n  \t\t# ,(\"testuser6@momenttext.com\",\"Password@123\",\"newPassword@1234\")\n  \t\t# ,(\"testuser7@momenttext.com\",\"Password@123\",\"newPassword@1234\")\n  \t\t# ,(\"testuser8@momenttext.com\",\"Password@123\",\"newPassword@1234\")\n  \t\t])\n  \tdef test_new_password_valid_data(self,client,email,password,new_pass,setup_saved_password):\nE       fixture 'setup_saved_password' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_activitylogs, setup_company, setup_invalid_attempt_update, setup_invalid_first_attempt, setup_multiple_invalid, setup_multiple_invalid_for_pass_reset, setup_multiple_invalid_reset, setup_random_user, setup_register_access, setup_register_worker, setup_roles, setup_saved_user, setup_superusers, setup_temporary_urls, setup_update_password, setup_update_password_access_counter, setup_user, setup_user_without_access, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py:524\n", "test_name": "test_new_password_valid_data[testuser1@momenttext.com-Password@123-newPassword@1234]", "rerun": "0"}, "1": {"status": "ERROR", "message": "file D:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py, line 545\n  \tdef test_new_password(self,client,setup_saved_password):\nE       fixture 'setup_saved_password' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, celery_app, celery_class_tasks, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, client, db, depends_on_current_app, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, enable_db_access_for_all_tests, faker, live_server, mailoutbox, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_activitylogs, setup_company, setup_invalid_attempt_update, setup_invalid_first_attempt, setup_multiple_invalid, setup_multiple_invalid_for_pass_reset, setup_multiple_invalid_reset, setup_random_user, setup_register_access, setup_register_worker, setup_roles, setup_saved_user, setup_superusers, setup_temporary_urls, setup_update_password, setup_update_password_access_counter, setup_user, setup_user_without_access, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db, use_celery_app_trap\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\projects\\backend\\backend\\usermanagement\\Test_usermanagement\\test_views.py:545\n", "test_name": "test_new_password", "rerun": "0"}}, "suite_name": "usermanagement/Test_usermanagement/test_views.py"}}}, "date": "August 19, 2021", "start_time": 1629387774.883106, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "2", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}